;;; cobalt2-theme.el --- Default Visual Studio Code Dark+ theme -*- lexical-binding: t; -*-

;; Copyright (C) 2020-2021 Timothy Bump

;; Author: Timothy Bump
;; URL: https://gitlab.com/__tpb/cobalt2-emacs-theme
;; Version: 0.0.0

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <https://www.gnu.org/licenses/>.

;; This file is not part of Emacs.

;;; Commentary:
;; A complete port of the popular cobalt2 vscode theme by Wes Bos.

;;; Code:

(deftheme cobalt2)

(defcustom cobalt2-box-hl-line nil
  "Set box around hl-line to mimic vscode border.
and add depth. Annoyingly causes text to
shift 1px to the right"
  :type 'boolean
  :group 'cobalt2)

(defcustom cobalt2-scale-org-faces t
  "Scale headlines and other org faces."
  :type 'boolean
  :group 'cobalt2)

(defcustom cobalt2-invert-hl-todo t
  "Set (:invert-video t) on hl-todo face."
  :type 'boolean
  :group 'cobalt2)

(let ((class '((class color) (min-colors 89)))
      (fg0               "#e1efff")
      (fg1               "#ffffff") ; default fg
      (fg2               "#c6c6c6")
      (fg3               "#aaaaaa")
      (fg4               "#8d9397")
      (bg0               "#15232d") ; solaire/mode-line
      (bg05              "#122738") ; tab-line
      (bg1               "#163042") ; gutter
      (bg2               "#193549") ; default bg
      (bg3               "#1f4662") ; hl line
      (bg4               "#234e6d") ; hl line box
      (bg5               "#0d3a58") ; window border
      (bg6               "#3b5364") ; indent guide
      (bg-hl             "#0050a4")

;; standardized palette
      (bos-yellow         "#ffc600")
      (bos-lightyellow    "#ffee80")
      (bos-darkcyan       "#80fcff")
      (bos-cyan           "#9effff")
      (bos-lightpink      "#ff628c")
      (bos-pink           "#ff0088")
      (bos-magenta        "#ff68b8")
      (bos-lightmagenta   "#fb94ff")
      (bos-orange         "#ff9d00")
      (bos-lightorange    "#ffb454")
      (bos-red            "#a22929")
      (bos-darkgreen      "#92fc79")
      (bos-aqua           "#80ffbb")
      (bos-blue           "#0088ff")
      (bos-lightred       "#F44542")
      (bos-green          "#a5ff90")
      (bos-lightblue      "#e1efff")
      (bos-purple         "#b267e6")
      (bos-blue-bg        "#0c4276")
      (bos-red-bg         "#443647")
      (bos-green-bg       "#20553a")
      (bos-yellow-bg      "#607532")
      (bos-red-bghl       "#663746")
      (bos-green-bghl     "#266f2e")
      (bos-yellow-bghl    "#79583b")
      (vc-r               "#a22929")
      (vc-g               "#3c9f4a")
      (vc-b               "#26506d")
      (key2               "#ff9d00")
      (key3               "#80ffbb")
      (numeric            "#ff628c")
      (mode-line-bg       "#15242d")
      (mode-line-bg-inactive "#15242d")
      (line-num           "#aaaaaa")
      (line-num-current   "#c6c6c6")
      (builtin            "#ff9d00")
      (keyword            "#ff9d00")
      (const              "#ffc600")
      (comment            "#0088ff")
      (doc                "#0088ff")
      (doc-alt            "#0088ff")
      (func               "#ffc600")
      (str                "#a5ff90")
      (type               "#ffc600")
      (var                "#e1efff")
      (warning            "#a22929"))

  (custom-theme-set-faces
   'cobalt2
   `(default                                  ((,class (:background ,bg2 :foreground ,fg1))))

   `(font-lock-builtin-face                   ((,class (:foreground ,builtin))))
   `(font-lock-preprocessor-face              ((,class (:foreground ,bos-cyan))))
   `(font-lock-comment-face                   ((,class (:foreground ,comment :slant italic))))
   `(font-lock-negation-char-face             ((,class (:foreground ,const))))
   `(font-lock-reference-face                 ((,class (:foreground ,const))))
   `(font-lock-constant-face                  ((,class (:foreground ,const))))
   `(font-lock-doc-face                       ((,class (:foreground ,doc))))
   `(font-lock-function-name-face             ((,class (:foreground ,func :bold nil))))
   `(font-lock-keyword-face                   ((,class (:bold nil :foreground ,keyword))))
   `(font-lock-string-face                    ((,class (:foreground ,str))))
   `(font-lock-type-face                      ((,class (:foreground ,type ))))
   `(font-lock-variable-name-face             ((,class (:foreground ,var))))
   `(font-lock-warning-face                   ((,class (:foreground ,warning :background ,bg2))))
   `(font-lock-regexp-grouping-backslash      ((,class (:foreground ,bos-lightorange))))
   `(font-lock-regexp-grouping-construct      ((,class (:foreground ,bos-lightorange))))

   `(region                                   ((,class (:background ,bg-hl :distant-foreground ,fg1 :extend nil))))
   `(secondary-selection                      ((,class (:background ,bos-blue-bg))))
   `(highlight                                ((,class (:inherit region)))) ; link hover
   `(hl-line                                  ((,class (:background ,bg3 :box (:line-width -1 :color ,bg4)))))
   `(fringe                                   ((,class (:background ,bg1 :foreground ,fg4))))
   `(cursor                                   ((,class (:background ,bos-yellow))))
   `(show-paren-match                         ((t (:foreground ,fg1 :background ,bos-blue :bold t))))
   `(show-paren-mismatch                      ((t (:background ,warning))))
   `(isearch                                  ((,class (:background ,bos-yellow-bghl))))
   `(shadow                                   ((,class (:foreground ,fg4))))
   `(vertical-border                          ((,class (:foreground ,bg5))))
   `(window-divider                           ((,class (:inherit vertical-border))))
   `(minibuffer-prompt                        ((,class (:foreground ,bos-cyan :weight normal))))
   `(link                                     ((,class (:foreground ,bos-blue))))
   `(error                                    ((,class (:foreground ,bos-orange :background ,bg0))))
   `(warning                                  ((,class (:foreground ,bos-magenta :background ,bg0))))
   `(success                                  ((,class (:foreground ,bos-cyan))))
   `(dired-directory                          ((t (:inherit (font-lock-keyword-face)))))
   `(line-number                              ((,class (:background ,bg1 :foreground ,line-num))))
   `(line-number-current-line                 ((,class (:background ,bg1 :foreground ,line-num-current))))
   `(header-line                              ((,class (:bold nil :foreground ,fg4 :background ,bg2))))

   `(mode-line                                ((,class (:bold nil :foreground ,fg3 :background ,mode-line-bg
                                                              :box (:color ,bg5)))))
   `(mode-line-inactive                       ((,class (:bold nil :foreground ,fg4 :background ,mode-line-bg-inactive
                                                              :box (:color ,bg5)))))
   `(mode-line-buffer-id                      ((,class (:bold nil :foreground ,fg0 :background nil))))
   `(mode-line-highlight                      ((,class (:foreground ,keyword :box nil :weight normal))))
   `(mode-line-emphasis                       ((,class (:foreground ,bos-yellow))))

   `(company-preview-common                   ((t (:foreground unspecified :background ,bg0))))
   `(company-scrollbar-bg                     ((t (:background ,bg0))))
   `(company-scrollbar-fg                     ((t (:background ,bg3))))
   `(company-tooltip                          ((t (:inherit default :background ,bg0))))
   `(company-tooltip-common                   ((t (:foreground ,bos-blue :bold t))))
   `(company-tooltip-selection                ((t (:background ,bg-hl))))
   `(company-tooltip-annotation               ((t (:foreground ,doc-alt)))) ; parameter hints etc.
   `(company-template-field                   ((t (:inherit region))))

   `(org-level-1                              ((,class (:bold t :foreground ,fg1
                                                              ,@(when cobalt2-scale-org-faces (list :height 1.3))))))
   `(org-level-2                              ((,class (:bold t :foreground ,fg0
                                                              ,@(when cobalt2-scale-org-faces (list :height 1.2))))))
   `(org-level-3                              ((,class (:bold nil :foreground ,fg1
                                                              ,@(when cobalt2-scale-org-faces (list :height 1.15))))))
   `(org-level-4                              ((,class (:bold nil :foreground ,fg0
                                                              ,@(when cobalt2-scale-org-faces (list :height 1.1))))))
   `(org-level-5                              ((,class (:bold nil :foreground ,fg1))))
   `(org-drawer                               ((,class (:foreground ,fg3))))
   `(org-code                                 ((,class (:foreground ,bos-orange))))
   `(org-hide                                 ((,class (:foreground ,bg2))))
   `(org-date                                 ((,class (:underline t :inherit link))))
   `(org-meta-line                            ((,class (:background ,bg2 :foreground ,fg3))))
   `(org-footnote                             ((,class (:underline t :foreground ,fg4))))
   `(org-link                                 ((,class (:underline t :foreground ,bos-blue ))))
   `(org-special-keyword                      ((,class (:foreground ,fg4))))
   `(org-property-value                       ((,class (:foreground ,bos-blue))))
   `(org-block-begin-line                     ((,class (:background ,bg1 :foreground ,fg4 :extend t))))
   `(org-block-end-line                       ((,class (:inherit 'org-block-begin-line :extend t))))
   `(org-block                                ((,class (:foreground ,fg2 :background ,bg05 :extend t))))
   `(org-quote                                ((,class (:inherit org-block :slant italic))))
   `(org-verse                                ((,class (:inherit org-block :slant italic))))
   `(org-todo                                 ((,class (:foreground ,bos-lightred))))
   `(org-headline-todo                        ((,class (:foreground ,bos-lightpink))))
   `(org-done                                 ((,class (:foreground ,vc-g))))
   `(org-headline-done                        ((,class (:foreground ,fg3))))
   `(org-warning                              ((,class (:underline t :foreground ,bos-pink))))
   `(org-agenda-structure                     ((,class (:height 1.15 :weight bold :foreground ,fg2 :background ,bg0))))
   `(org-agenda-structure-secondary           ((,class (:weight normal :foreground ,fg2 :background ,bg0))))
   `(org-agenda-structure-filter              ((,class (:foreground ,bos-lightred))))
   `(org-agenda-date                          ((,class (:foreground ,fg1 ,@(when cobalt2-scale-org-faces (list :height 1.1))))))
   `(org-agenda-date-weekend                  ((,class (:weight normal :foreground ,fg3))))
   `(org-agenda-date-today                    ((,class (:weight normal :foreground ,const
                                                                ,@(when cobalt2-scale-org-faces (list :height 1.2))))))
   `(org-agenda-done                          ((,class (:foreground ,bg6))))
   `(org-agenda-calendar-event                ((,class (:foreground ,fg3))))
   `(org-scheduled                            ((,class (:foreground ,type))))
   `(org-scheduled-previously                 ((,class (:foreground ,bos-orange))))
   `(org-upcoming-distant-deadline            ((,class (:foreground ,bos-lightorange))))
   `(org-imminent-deadline                    ((,class (:foreground ,bos-lightred :background ,bos-red-bg))))
   `(org-scheduled-today                      ((,class (:foreground ,func :weight normal
                                                                    ,@(when cobalt2-scale-org-faces (list :height 1.2))))))
   `(org-ellipsis                             ((,class (:foreground ,builtin))))
   `(org-verbatim                             ((,class (:foreground ,bos-lightorange))))
   `(org-document-title                       ((,class (:foreground ,bos-cyan :bold t
                                                                    ,@(when cobalt2-scale-org-faces (list :height 1.2)))))) ; title
   `(org-document-info                        ((,class (:foreground ,bos-yellow)))) ; author, date etc.
   `(org-document-info-keyword                ((,class (:foreground ,fg3))))  ; "#+Title", "#+Date" etc.
   `(org-sexp-date                            ((,class (:foreground ,fg4))))
   `(org-table                                ((,class (:inherit org-block))))
   `(org-tag                                  ((,class (:foreground ,comment))))
   `(font-latex-bold-face                     ((,class (:foreground ,type))))
   `(font-latex-italic-face                   ((,class (:foreground ,key3 :italic t))))
   `(font-latex-string-face                   ((,class (:foreground ,str))))
   `(font-latex-match-reference-keywords      ((,class (:foreground ,const))))
   `(font-latex-match-variable-keywords       ((,class (:foreground ,var))))

   `(ido-only-match                           ((,class (:foreground ,keyword))))
   `(ido-subdir                               ((,class (:weight normal :foreground ,fg0))))
   `(ido-first-match                          ((,class (:foreground ,keyword :bold nil))))

   `(gnus-header-content                      ((,class (:foreground ,keyword))))
   `(gnus-header-from                         ((,class (:foreground ,var))))
   `(gnus-header-name                         ((,class (:foreground ,type))))
   `(gnus-header-subject                      ((,class (:foreground ,func :bold nil))))

   `(mu4e-view-url-number-face                ((,class (:foreground ,type))))
   `(mu4e-cited-1-face                        ((,class (:foreground ,fg2))))
   `(mu4e-cited-7-face                        ((,class (:foreground ,fg3))))
   `(mu4e-header-marks-face                   ((,class (:foreground ,type))))

   `(ffap                                     ((,class (:foreground ,fg4))))

   `(js2-private-function-call                ((,class (:foreground ,const))))
   `(js2-jsdoc-html-tag-delimiter             ((,class (:foreground ,str))))
   `(js2-jsdoc-html-tag-name                  ((,class (:foreground ,key2))))
   `(js2-external-variable                    ((,class (:foreground ,type  ))))
   `(js2-function-param                       ((,class (:foreground ,const))))
   `(js2-jsdoc-value                          ((,class (:foreground ,str))))
   `(js2-private-member                       ((,class (:foreground ,fg3))))
   `(js2-warning                              ((t (:underline ,warning))))
   `(js2-error                                ((t (:foreground ,warning :weight normal))))
   `(js2-jsdoc-tag                            ((t (:foreground ,var))))
   `(js2-jsdoc-type                           ((t (:foreground ,var))))
   `(js2-instance-member                      ((t (:foreground ,var))))
   `(js2-object-property                      ((t (:foreground ,func))))
   `(js2-magic-paren                          ((t (:foreground ,const))))
   `(js2-function-call                        ((t (:foreground ,const))))
   `(js2-keywords                             ((t (:foreground ,keyword))))
   `(js3-warning-face                         ((,class (:underline ,keyword))))
   `(js3-error-face                           ((,class (:underline ,warning))))
   `(js3-external-variable-face               ((,class (:foreground ,var))))
   `(js3-function-param-face                  ((,class (:foreground ,key3))))
   `(js3-jsdoc-tag-face                       ((,class (:foreground ,keyword))))
   `(js3-instance-member-face                 ((,class (:foreground ,const))))

   `(ac-completion-face                       ((,class (:underline t :foreground ,keyword))))
   `(info-quoted-name                         ((,class (:foreground ,builtin))))
   `(info-string                              ((,class (:foreground ,str))))
   `(icompletep-determined                    ((,class :foreground ,builtin)))

   `(slime-repl-inputed-output-face           ((,class (:foreground ,type))))
   `(trailing-whitespace                      ((,class :foreground nil :background ,warning)))
   `(lazy-highlight                           ((,class (:background ,bos-yellow-bg))))

   `(undo-tree-visualizer-current-face        ((,class :foreground ,builtin)))
   `(undo-tree-visualizer-default-face        ((,class :foreground ,fg2)))
   `(undo-tree-visualizer-unmodified-face     ((,class :foreground ,var)))
   `(undo-tree-visualizer-register-face       ((,class :foreground ,type)))

   `(rainbow-delimiters-depth-1-face          ((,class :foreground "gold")))
   `(rainbow-delimiters-depth-2-face          ((,class :foreground "orchid")))
   `(rainbow-delimiters-depth-3-face          ((,class :foreground "LightSkyBlue")))
   `(rainbow-delimiters-depth-4-face          ((,class :foreground "gold")))
   `(rainbow-delimiters-depth-5-face          ((,class :foreground "orchid")))
   `(rainbow-delimiters-depth-6-face          ((,class :foreground "LightSkyBlue")))
   `(rainbow-delimiters-depth-7-face          ((,class :foreground "gold")))
   `(rainbow-delimiters-depth-8-face          ((,class :foreground "orchid")))
   `(rainbow-delimiters-depth-9-face          ((,class :foreground "LightSkyBlue")))
   `(rainbow-delimiters-unmatched-face        ((,class :foreground ,warning)))

   `(magit-item-highlight                     ((,class :background ,bg3)))
   `(magit-hunk-heading                       ((,class (:background ,bg3))))
   `(magit-hunk-heading-highlight             ((,class (:background ,bg3))))
   `(magit-bisect-bad                         ((t (:foreground ,bos-red))))
   `(magit-bisect-good                        ((t (:foreground ,bos-green))))
   `(magit-bisect-skip                        ((t (:foreground ,bos-orange))))
   `(magit-blame-date                         ((t (:foreground ,bos-red))))
   `(magit-blame-heading                      ((t (:foreground ,bos-orange :background ,bg3 :extend t))))
   `(magit-branch                             ((,class (:foreground ,bos-yellow :weight normal))))
   `(magit-branch-current                     ((t (:foreground ,bos-yellow))))
   `(magit-branch-local                       ((t (:foreground ,bos-cyan))))
   `(magit-branch-remote                      ((t (:foreground ,bos-green))))
   `(magit-cherry-equivalent                  ((t (:foreground ,bos-magenta))))
   `(magit-cherry-unmatched                   ((t (:foreground ,bos-cyan))))
   `(magit-diff-added                         ((t (:foreground ,fg0 :background ,bos-green-bg :extend t))))
   `(magit-diff-added-highlight               ((t (:foreground ,fg1 :background ,bos-green-bghl :extend t))))
   `(magit-diff-removed                       ((t (:foreground ,fg0 :background ,bos-red-bg :extend t))))
   `(magit-diff-removed-highlight             ((t (:foreground ,fg1 :background ,bos-red-bghl :extend t))))
   `(magit-diff-base                          ((t (:foreground ,bg2 :background ,bos-orange :extend t))))
   `(magit-diff-base-highlight                ((t (:foreground ,bos-orange :background ,bg3 :extend t))))
   `(magit-diff-context                       ((t (:foreground ,fg0 :extend t))))
   `(magit-diff-context-highlight             ((,class (:foreground ,fg1 :background ,bg05))))
   `(magit-diff-file-header                   ((,class (:foreground ,fg2 :background ,bg3))))
   `(magit-diff-file-heading                  ((t (:foreground ,fg1 :extend t))))
   `(magit-diff-file-heading-highlight        ((t (:background ,bg3 :extend t))))
   `(magit-diff-file-heading-selection        ((t (:foreground ,bos-orange :background ,bg3 :extend t))))
   `(magit-diff-hunk-heading                  ((t (:foreground ,fg1 :background ,bg3 :extend t))))
   `(magit-diff-hunk-heading-highlight        ((t (:background ,bg3 :extend t))))
   `(magit-diff-lines-heading                 ((t (:foreground ,bos-yellow :background ,bos-red :extend t))))
   `(magit-diffstat-added                     ((t (:foreground ,bos-green))))
   `(magit-diffstat-removed                   ((t (:foreground ,bos-orange))))
   `(magit-dimmed                             ((t (:foreground ,comment))))
   `(magit-filename                           ((t (:foreground ,bos-magenta))))
   `(magit-hash                               ((t (:foreground ,comment))))
   `(magit-header-line                        ((t (:inherit nil))))
   `(magit-log-author                         ((t (:foreground ,bos-orange))))
   `(magit-log-date                           ((t (:foreground ,bos-blue))))
   `(magit-log-graph                          ((t (:foreground ,comment))))
   `(magit-mode-line-process                  ((t (:foreground ,bos-orange))))
   `(magit-mode-line-process-error            ((t (:foreground ,bos-red))))
   `(magit-process-ok                         ((t (:inherit success))))
   `(magit-process-ng                         ((t (:inherit error))))
   `(magit-reflog-amend                       ((t (:foreground ,bos-magenta))))
   `(magit-reflog-checkout                    ((t (:foreground ,bos-blue))))
   `(magit-reflog-cherry-pick                 ((t (:foreground ,bos-green))))
   `(magit-reflog-commit                      ((t (:foreground ,bos-green))))
   `(magit-reflog-merge                       ((t (:foreground ,bos-green))))
   `(magit-reflog-other                       ((t (:foreground ,bos-cyan))))
   `(magit-reflog-rebase                      ((t (:foreground ,bos-magenta))))
   `(magit-reflog-remote                      ((t (:foreground ,bos-cyan))))
   `(magit-reflog-reset                       ((t (:inherit error))))
   `(magit-refname                            ((t (:foreground ,comment))))
   `(magit-section-heading                    ((t (:foreground ,bos-magenta))))
   `(magit-section-heading-selection          ((t (:foreground ,bos-orange :extend t))))
   `(magit-section-highlight                  ((t (:background ,bg3 :extend t))))
   `(magit-sequence-drop                      ((t (:foreground ,bos-red))))
   `(magit-sequence-head                      ((t (:foreground ,bos-blue))))
   `(magit-sequence-part                      ((t (:foreground ,bos-orange))))
   `(magit-sequence-stop                      ((t (:foreground ,bos-green))))
   `(magit-signature-bad                      ((t (:inherit error))))
   `(magit-signature-error                    ((t (:inherit error))))
   `(magit-signature-expired-key              ((t (:foreground ,bos-orange))))
   `(magit-signature-good                     ((t (:inherit success))))
   `(magit-signature-revoked                  ((t (:foreground ,bos-magenta))))
   `(magit-signature-untrusted                ((t (:foreground ,bos-cyan))))
   `(magit-tag                                ((t (:foreground ,bos-yellow))))

   `(git-commit-summary                       ((t (:inherit default)))) ; magit commit message face

   `(term                                     ((,class (:foreground ,fg1 :background ,bg05))))
   `(term-color-black                         ((,class (:foreground ,bg3 :background ,bg3))))
   `(term-color-blue                          ((,class (:foreground ,bos-blue :background ,func))))
   `(term-color-red                           ((,class (:foreground ,bos-red :background ,bg3))))
   `(term-color-green                         ((,class (:foreground ,bos-green :background ,bg3))))
   `(term-color-yellow                        ((,class (:foreground ,bos-yellow :background ,var))))
   `(term-color-magenta                       ((,class (:foreground ,bos-magenta :background ,builtin))))
   `(term-color-cyan                          ((,class (:foreground ,bos-cyan :background ,str))))
   `(term-color-white                         ((,class (:foreground ,fg1 :background ,fg2))))

   `(diredfl-autofile-name                    ((t (:foreground ,fg0))))
   `(diredfl-compressed-file-name             ((t (:foreground ,bos-yellow))))
   `(diredfl-compressed-file-suffix           ((t (:foreground ,doc-alt))))
   `(diredfl-date-time                        ((t (:foreground ,bos-cyan))))
   `(diredfl-deletion                         ((t (:foreground ,bos-red :bold t))))
   `(diredfl-deletion-file-name               ((t (:foreground ,bos-red ))))
   `(diredfl-dir-heading                      ((t (:foreground ,bos-blue :bold t))))
   `(diredfl-dir-name                         ((t (:foreground ,bos-blue))))
   `(diredfl-dir-priv                         ((t (:foreground ,bos-blue))))
   `(diredfl-exec-priv                        ((t (:foreground ,bos-green))))
   `(diredfl-executable-tag                   ((t (:foreground ,bos-green))))
   `(diredfl-file-name                        ((t (:foreground ,fg1))))
   `(diredfl-file-suffix                      ((t (:foreground ,doc-alt))))
   `(diredfl-flag-mark                        ((t (:foreground ,bos-yellow :bold t))))
   `(diredfl-ignored-file-name                ((t (:foreground ,doc-alt))))
   `(diredfl-link-priv                        ((t (:foreground ,bos-magenta))))
   `(diredfl-no-priv                          ((t (:foreground ,fg1))))
   `(diredfl-number                           ((t (:foreground ,bos-orange))))
   `(diredfl-other-priv                       ((t (:foreground ,bos-magenta))))
   `(diredfl-rare-priv                        ((t (:foreground ,fg1))))
   `(diredfl-read-priv                        ((t (:foreground ,bos-yellow))))
   `(diredfl-symlink                          ((t (:foreground ,bos-magenta))))
   `(diredfl-tagged-autofile-name             ((t (:foreground ,fg0))))
   `(diredfl-write-priv                       ((t (:foreground ,bos-red))))

   `(helm-header                              ((,class (:foreground ,fg2 :background ,bg2 :underline nil :box nil))))
   `(helm-source-header                       ((,class (:foreground ,keyword :background ,bg2 :underline nil :weight normal))))
   `(helm-selection                           ((,class (:background ,bg-hl :underline nil :extend t))))
   `(helm-selection-line                      ((,class (:background ,bg-hl :extend t))))
   `(helm-visible-mark                        ((,class (:foreground ,bg2 :background ,bg3))))
   `(helm-candidate-number                    ((,class (:foreground ,bg2 :background ,fg1))))
   `(helm-separator                           ((,class (:foreground ,type :background ,bg2))))
   `(helm-time-zone-current                   ((,class (:foreground ,builtin :background ,bg2))))
   `(helm-time-zone-home                      ((,class (:foreground ,type :background ,bg2))))
   `(helm-buffer-not-saved                    ((,class (:foreground ,type :background ,bg2))))
   `(helm-buffer-process                      ((,class (:foreground ,builtin :background ,bg2))))
   `(helm-buffer-saved-out                    ((,class (:foreground ,fg1 :background ,bg2))))
   `(helm-buffer-size                         ((,class (:foreground ,fg1 :background ,bg2))))
   `(helm-ff-directory                        ((,class (:foreground ,func :background ,bg2 :weight normal))))
   `(helm-ff-file                             ((,class (:foreground ,fg1 :background ,bg2 :weight normal))))
   `(helm-ff-executable                       ((,class (:foreground ,key2 :background ,bg2 :weight normal))))
   `(helm-ff-invalid-symlink                  ((,class (:foreground ,key3 :background ,bg2 :weight normal))))
   `(helm-ff-symlink                          ((,class (:foreground ,keyword :background ,bg2 :weight normal))))
   `(helm-ff-prefix                           ((,class (:foreground ,bg2 :background ,keyword :weight normal))))
   `(helm-grep-cmd-line                       ((,class (:foreground ,fg1 :background ,bg2))))
   `(helm-grep-file                           ((,class (:foreground ,fg1 :background ,bg2))))
   `(helm-grep-finish                         ((,class (:foreground ,fg2 :background ,bg2))))
   `(helm-grep-lineno                         ((,class (:foreground ,fg1 :background ,bg2))))
   `(helm-grep-match                          ((,class (:foreground nil :background nil :inherit helm-match))))
   `(helm-grep-running                        ((,class (:foreground ,func :background ,bg2))))
   `(helm-moccur-buffer                       ((,class (:foreground ,func :background ,bg2))))
   `(helm-source-go-package-godoc-description ((,class (:foreground ,str))))
   `(helm-bookmark-w3m                        ((,class (:foreground ,type))))

   `(web-mode-html-tag-bracket-face           ((,class (:foreground "#808080"))))
   `(web-mode-html-tag-face                   ((,class (:foreground ,keyword))))
   `(web-mode-html-attr-name-face             ((,class (:foreground ,var))))
   `(web-mode-html-attr-value-face            ((,class (:foreground ,str))))
   `(web-mode-html-attr-equal-face            ((,class (:foreground ,fg1))))
   `(web-mode-builtin-face                    ((,class (:inherit ,font-lock-builtin-face))))
   `(web-mode-comment-face                    ((,class (:inherit ,font-lock-comment-face))))
   `(web-mode-constant-face                   ((,class (:inherit ,font-lock-constant-face))))
   `(web-mode-keyword-face                    ((,class (:foreground ,keyword))))
   `(web-mode-doctype-face                    ((,class (:inherit ,font-lock-doc-face))))
   `(web-mode-function-name-face              ((,class (:inherit ,font-lock-function-name-face))))
   `(web-mode-string-face                     ((,class (:foreground ,str))))
   `(web-mode-type-face                       ((,class (:inherit ,font-lock-type-face))))
   `(web-mode-warning-face                    ((,class (:inherit ,font-lock-warning-face))))
   `(web-mode-json-key-face                   ((,class (:foreground ,str))))
   `(web-mode-json-context-face               ((,class (:foreground ,str))))

   `(diff-header                              ((t (:foreground ,bos-cyan :background nil))))
   `(diff-file-header                         ((t (:foreground ,fg3 :background nil))))
   `(diff-hunk-header                         ((t (:foreground ,fg4 :background ,bg3))))
   `(diff-added                               ((t (:foreground ,fg2 :background ,bos-green-bg))))
   `(diff-removed                             ((t (:foreground ,fg2 :background ,bos-red-bg))))
   `(diff-changed                             ((t (:foreground ,fg2 :background ,bos-yellow-bg))))
   `(diff-refine-added                        ((t (:foreground ,fg3 :background ,bos-green-bghl))))
   `(diff-refine-removed                      ((t (:foreground ,fg3 :background ,bos-red-bghl))))
   `(diff-refine-changed                      ((t (:foreground ,fg3 :background ,bos-yellow-bghl))))

   `(ediff-fine-diff-Ancestor                 ((t (:background ,bos-red-bghl))))
   `(ediff-fine-diff-A                        ((t (:background ,bos-red-bghl))))
   `(ediff-fine-diff-B                        ((t (:background ,bos-green-bghl))))
   `(ediff-fine-diff-C                        ((t (:background ,bos-yellow-bghl))))
   `(ediff-current-diff-Ancestor              ((t (:background ,bos-red-bg))))
   `(ediff-current-diff-A                     ((t (:background ,bos-red-bg))))
   `(ediff-current-diff-B                     ((t (:background ,bos-green-bg))))
   `(ediff-current-diff-C                     ((t (:background ,bos-yellow-bg))))
   `(ediff-even-diff-Ancestor                 ((t (:background ,bg3))))
   `(ediff-even-diff-A                        ((t (:background ,bg3))))
   `(ediff-even-diff-B                        ((t (:background ,bg3))))
   `(ediff-even-diff-C                        ((t (:background ,bg3))))
   `(ediff-odd-diff-Ancestor                  ((t (:background ,bg3))))
   `(ediff-odd-diff-A                         ((t (:background ,bg3))))
   `(ediff-odd-diff-B                         ((t (:background ,bg3))))
   `(ediff-odd-diff-C                         ((t (:background ,bg3))))

   `(jde-java-font-lock-package-face          ((t (:foreground ,var))))
   `(jde-java-font-lock-public-face           ((t (:foreground ,keyword))))
   `(jde-java-font-lock-private-face          ((t (:foreground ,keyword))))
   `(jde-java-font-lock-constant-face         ((t (:foreground ,const))))
   `(jde-java-font-lock-modifier-face         ((t (:foreground ,key3))))
   `(jde-jave-font-lock-protected-face        ((t (:foreground ,keyword))))
   `(jde-java-font-lock-number-face           ((t (:foreground ,numeric))))

   `(centaur-tabs-default                     ((t (:background ,bg05 :foreground ,fg1))))
   `(centaur-tabs-selected                    ((t (:background ,bg2 :foreground ,fg1 :box nil))))
   `(centaur-tabs-unselected                  ((t (:background ,bg05 :foreground ,fg3 :box nil))))
   `(centaur-tabs-selected-modified           ((t (:background ,bg2 :foreground ,bos-yellow :box nil))))
   `(centaur-tabs-unselected-modified         ((t (:background ,bg05 :foreground ,bos-yellow :box nil))))
   `(centaur-tabs-active-bar-face             ((t (:background ,bos-yellow :box nil))))
   `(centaur-tabs-modified-marker-selected    ((t (:inherit 'centaur-tabs-selected-modified :foreground ,fg1 :box nil))))
   `(centaur-tabs-modified-marker-unselected  ((t (:inherit 'centaur-tabs-unselected-modified :foreground ,fg1 :box nil))))

   `(corfu-bar                                ((t (:background ,fg3))))
   `(corfu-border                             ((t (:background ,bos-blue-bg))))
   `(corfu-current                            ((t (:background ,bg-hl))))
   `(corfu-default                            ((t (:background ,bg0 :foreground ,fg1))))

   ;; Marginalia looks good by default
   ;; Vertico looks good by default

   `(orderless-match-face-0 ((t (:foreground ,bos-yellow))))
   `(orderless-match-face-1 ((t (:foreground ,bos-magenta))))
   `(orderless-match-face-2 ((t (:foreground ,bos-lightyellow))))
   `(orderless-match-face-3 ((t (:foreground ,bos-orange))))

   `(treemacs-file-face                       ((t (:foreground ,fg3))))
   `(treemacs-root-face                       ((t (:foreground ,fg3 :height 1.2 :weight bold))))
   `(treemacs-directory-face                  ((t (:foreground ,fg3))))
   `(treemacs-git-added-face                  ((t (:foreground ,bos-aqua))))
   `(treemacs-git-ignored-face                ((t (:foreground ,fg4))))
   `(treemacs-git-modified-face               ((t (:foreground ,bos-yellow))))
   `(treemacs-git-untracked-face              ((t (:foreground ,bos-lightpink))))
   `(treemacs-all-the-icons-file-face         ((t (:foreground ,fg3))))
   `(treemacs-all-the-icons-root-face         ((t (:foreground ,fg2))))
   `(treemacs-directory-collapsed-face        ((t (:foreground ,fg3))))

   `(solaire-default-face                     ((t (:inherit default :background ,bg0))))
   `(solaire-hl-line-face                     ((t (:inherit hl-line :background ,bg2))))
   `(solaire-org-hide-face                    ((t (:inherit org-hide :background ,bg0))))

   `(highlight-indent-guides-character-face     ((t (:foreground ,bg6))))

   `(ivy-confirm-face                         ((t (:inherit minibuffer-prompt :foreground ,keyword))))
   `(ivy-current-match                        ((t (:background ,bg-hl :extend t))))
   `(ivy-highlight-face                       ((t (:inherit font-lock-builtin-face))))
   `(ivy-match-required-face                  ((t (:inherit minibuffer-prompt :foreground ,warning))))
   `(ivy-minibuffer-match-face-1              ((t (:inherit isearch))))
   `(ivy-minibuffer-match-face-2              ((t (:inherit ivy-minibuffer-match-face-1))))
   `(ivy-minibuffer-match-face-3              ((t (:inherit ivy-minibuffer-match-face-2))))
   `(ivy-minibuffer-match-face-4              ((t (:inherit ivy-minibuffer-match-face-2))))
   `(ivy-minibuffer-match-highlight           ((t (:inherit ivy-current-match))))
   `(ivy-modified-buffer                      ((t (:inherit default :foreground ,var))))
   `(ivy-virtual                              ((t (:inherit default :foreground ,doc-alt))))

   `(counsel-key-binding                      ((t (:foreground ,var))))

   `(swiper-match-face-1                      ((t (:inherit ivy-minibuffer-match-face-1))))
   `(swiper-match-face-2                      ((t (:inherit ivy-minibuffer-match-face-2))))
   `(swiper-match-face-3                      ((t (:inherit ivy-minibuffer-match-face-3))))
   `(swiper-match-face-4                      ((t (:inherit ivy-minibuffer-match-face-4))))
   `(swiper-line-face                         ((t (:foreground ,fg0 :background ,bg4 :extend t))))

   `(git-gutter:added                         ((t (:background ,vc-g :foreground ,vc-g :weight normal))))
   `(git-gutter:deleted                       ((t (:background ,vc-r :foreground ,vc-r :weight normal))))
   `(git-gutter:modified                      ((t (:background ,vc-b :foreground ,vc-b :weight normal))))
   `(git-gutter-fr:added                      ((t (:background ,vc-g :foreground ,vc-g :weight normal))))
   `(git-gutter-fr:deleted                    ((t (:background ,vc-r :foreground ,vc-r :weight normal))))
   `(git-gutter-fr:modified                   ((t (:background ,vc-b :foreground ,vc-b :weight normal))))

   `(diff-hl-insert                           ((t (:background ,vc-g :foreground ,vc-g))))
   `(diff-hl-delete                           ((t (:background ,vc-r :foreground ,vc-r))))
   `(diff-hl-change                           ((t (:background ,vc-b :foreground ,vc-b))))

   `(neo-dir-link-face                        ((t (:foreground "#cccccc"))))
   `(neo-header-face                          ((t (:foreground "#cccccc"))))
   `(neo-banner-face                          ((t (:foreground "#cccccc"))))
   `(neo-root-dir-face                        ((t (:foreground "#cccccc"))))
   `(neo-file-link-face                       ((t (:foreground "#cccccc"))))
   `(neo-expand-btn-face                      ((t (:foreground "#cccccc"))))

   `(sml/global                               ((t (:foreground ,fg2 :weight normal))))
   `(sml/filename                             ((t (:foreground ,fg2 :weight normal))))
   `(sml/line-number                          ((t (:foreground ,fg2 :weight normal))))
   `(sml/prefix                               ((t (:foreground ,fg2 :weight normal))))
   `(sml/read-only                            ((t (:foreground ,fg2 :weight normal))))
   `(sml/modes                                ((t (:foreground ,fg2 :weight normal))))
   `(sml/modified                             ((t (:foreground ,fg1 :weight bold))))
   `(sml/charging                             ((t (:foreground ,bos-green :weight normal))))

   `(evil-ex-substitute-matches               ((t (:foreground ,warning :weight normal :strike-through t))))
   `(evil-ex-substitute-replacement           ((t (:foreground ,bos-cyan :weight normal))))

   `(hl-todo                                  ((t ,@(when cobalt2-invert-hl-todo (list :inverse-video t)))))
   `(highlight-numbers-number                 ((t (:foreground ,numeric))))
   `(highlight-operators-face                 ((t (:inherit default))))
   `(highlight-symbol-face                    ((t (:background "#343a40"))))

   `(window-divider                           ((t (:foreground "gray40"))))
   `(window-divider-last-pixel                ((t (:foreground "gray20"))))
   `(window-divider-first-pixel               ((t (:foreground "gray60"))))

   `(tree-sitter-hl-face:method.call          ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:function             ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:function.macro       ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:function.call        ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:number               ((t (:inherit highlight-numbers-number))))
   `(tree-sitter-hl-face:variable.special     ((t (:inherit font-lock-keyword-face))))
   `(tree-sitter-hl-face:property.definition  ((t (:foreground ,bos-cyan :italic nil))))
   `(tree-sitter-hl-face:property             ((t (:foreground ,bos-cyan :italic nil))))
   `(tree-sitter-hl-face:constant.builtin     ((t (:foreground ,bos-lightpink))))
   `(tree-sitter-hl-face:punctuation          ((t (:foreground ,bos-orange))))
   `(tree-sitter-hl-face:punctuation.bracket  ((t (:foreground ,fg0))))
   `(tree-sitter-hl-face:constructor          ((t (:foreground ,fg0))))
   `(tree-sitter-hl-face:attribute            ((t (:foreground ,bos-cyan))))
   `(tree-sitter-hl-face:keyword              ((t (:inherit font-lock-keyword-face))))
   `(tree-sitter-hl-face:operator             ((t (:foreground ,bos-orange))))
   `(tree-sitter-hl-face:type                 ((t (:inherit font-lock-type-face))))
   `(tree-sitter-hl-face:type.builtin         ((t (:foreground ,bos-magenta :italic t))))

   `(lsp-ui-doc-background                    ((t (:background ,bg0))))
   `(lsp-headerline-breadcrumb-path-face      ((t (:inherit variable-pitch :foreground ,fg4))))
   `(lsp-headerline-breadcrumb-symbols-face   ((t (:inherit lsp-headerline-breadcrumb-path-face))))

   `(font-latex-bold-face                     ((t (:inherit bold))))
   `(font-latex-italic-face                   ((t (:inherit italic))))
   `(font-latex-math-face                     ((t (:foreground ,bos-blue))))
   `(font-latex-sectioning-0-face             ((t (:foreground ,bos-blue))))
   `(font-latex-sectioning-1-face             ((t (:foreground ,bos-magenta))))
   `(font-latex-sectioning-2-face             ((t (:foreground ,bos-lightorange))))
   `(font-latex-sectioning-3-face             ((t (:foreground ,bos-lightblue))))
   `(font-latex-sectioning-4-face             ((t (:foreground ,bos-lightred))))
   `(font-latex-sectioning-5-face             ((t (:foreground ,bos-darkgreen))))
   `(font-latex-script-char-face              ((t (:foreground ,bos-blue))))
   `(font-latex-string-face                   ((t (:inherit font-lock-string-face))))
   `(font-latex-warning-face                  ((t (:inherit font-lock-warning-face))))
   `(font-latex-verbatim-face                 ((t (:inherit org-verbatim))))
   `(TeX-error-description-error              ((t (:inherit error :bold t))))
   `(TeX-error-description-warning            ((t (:inherit warning :bold t))))
   `(TeX-error-description-tex-said           ((t (:inherit success :bold t))))

   `(tab-bar-tab-inactive                     ((t (:background ,bg05 :foreground ,fg3 :box nil))))
   `(tab-bar-tab                              ((t (:background ,bg2 :foreground ,fg1 :box nil))))
   `(tab-line                                 ((t (:background ,bg05))))
   `(tab-line-modified                        ((t (:foreground ,bos-yellow))))
   `(tab-line-tab-current                     ((t (:inherit tab-bar-tab))))
   `(tab-line-tab-inactive                    ((t (:inherit tab-bar-tab-inactive))))
   `(tab-line-tab                             ((t (:inherit tab-bar))))
   `(tab-bar                                  ((t (:background ,bg05))))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'cobalt2)
(provide 'cobalt2-theme)

;;; cobalt2-theme.el ends here
